import type {
  Deal,
  ServicePackage,
  Proposal,
  ActivityItem,
  Testimonial,
} from "@/types";

// ─── Service Packages (6) ───

export const seedServices: ServicePackage[] = [
  {
    id: "svc-001",
    name: "AI Strategy Workshop",
    description:
      "Intensive 2-day workshop to identify AI opportunities, build a roadmap, and align stakeholders on implementation priorities.",
    category: "consulting",
    tier: "starter",
    price: 4500,
    unit: "project",
    features: [
      "Stakeholder interviews",
      "AI opportunity mapping",
      "Technology assessment",
      "Implementation roadmap",
      "Executive summary report",
    ],
    deliverables: [
      "AI Opportunity Matrix",
      "90-Day Roadmap",
      "Executive Presentation",
    ],
    estimatedDuration: "2 days",
    isActive: true,
  },
  {
    id: "svc-002",
    name: "Custom LLM Integration",
    description:
      "End-to-end development of custom LLM-powered features integrated into your existing product or workflow.",
    category: "development",
    tier: "professional",
    price: 15000,
    unit: "project",
    features: [
      "Requirements analysis",
      "Model selection & fine-tuning",
      "API development",
      "Testing & validation",
      "Production deployment",
      "30-day support",
    ],
    deliverables: [
      "Deployed LLM API",
      "Integration documentation",
      "Performance benchmarks",
    ],
    estimatedDuration: "4-6 weeks",
    isActive: true,
  },
  {
    id: "svc-003",
    name: "AI Team Training",
    description:
      "Comprehensive training program to upskill your engineering team on AI/ML fundamentals and practical implementation.",
    category: "training",
    tier: "starter",
    price: 3000,
    unit: "project",
    features: [
      "Customized curriculum",
      "Hands-on workshops",
      "Code lab exercises",
      "Assessment & certification",
      "Resource library access",
    ],
    deliverables: [
      "Training materials",
      "Code lab repository",
      "Team assessment report",
    ],
    estimatedDuration: "1 week",
    isActive: true,
  },
  {
    id: "svc-004",
    name: "AI Infrastructure Audit",
    description:
      "Deep-dive analysis of your current AI/ML infrastructure, identifying bottlenecks, cost optimizations, and scaling opportunities.",
    category: "audit",
    tier: "professional",
    price: 8000,
    unit: "project",
    features: [
      "Infrastructure review",
      "Cost analysis",
      "Performance profiling",
      "Security assessment",
      "Scaling recommendations",
    ],
    deliverables: [
      "Audit report",
      "Cost optimization plan",
      "Architecture diagram",
    ],
    estimatedDuration: "2 weeks",
    isActive: true,
  },
  {
    id: "svc-005",
    name: "Enterprise AI Platform",
    description:
      "Full-scale AI platform development with custom models, data pipelines, monitoring, and team onboarding.",
    category: "development",
    tier: "enterprise",
    price: 50000,
    unit: "project",
    features: [
      "Platform architecture",
      "Custom model development",
      "Data pipeline engineering",
      "MLOps setup",
      "Monitoring & alerting",
      "Team onboarding",
      "6-month support",
    ],
    deliverables: [
      "Production AI platform",
      "Operations runbook",
      "Training documentation",
    ],
    estimatedDuration: "3-6 months",
    isActive: true,
  },
  {
    id: "svc-006",
    name: "Ongoing AI Support",
    description:
      "Dedicated AI support with model monitoring, fine-tuning, and priority access to our engineering team.",
    category: "support",
    tier: "professional",
    price: 5000,
    unit: "month",
    features: [
      "Model monitoring",
      "Performance optimization",
      "Monthly review calls",
      "Priority Slack access",
      "Quarterly model updates",
    ],
    deliverables: [
      "Monthly performance reports",
      "Model update releases",
      "Optimization recommendations",
    ],
    estimatedDuration: "Ongoing",
    isActive: true,
  },
];

// ─── Deals (8) ───

export const seedDeals: Deal[] = [
  {
    id: "deal-001",
    clientName: "Sarah Chen",
    clientEmail: "sarah@meridiantech.io",
    clientCompany: "Meridian Technologies",
    title: "Enterprise AI Platform Build",
    value: 52000,
    stage: "negotiation",
    priority: "high",
    probability: 75,
    serviceIds: ["svc-005"],
    proposalId: "prop-001",
    notes:
      "Strong interest from CTO. Budget approved Q1. Waiting on legal review.",
    createdAt: "2025-12-15T10:00:00Z",
    updatedAt: "2026-02-20T14:30:00Z",
    closedAt: null,
    nextFollowUp: "2026-02-27T10:00:00Z",
  },
  {
    id: "deal-002",
    clientName: "Marcus Rivera",
    clientEmail: "marcus@novahealth.com",
    clientCompany: "NovaHealth",
    title: "LLM-Powered Patient Triage",
    value: 18500,
    stage: "proposal",
    priority: "high",
    probability: 60,
    serviceIds: ["svc-002", "svc-004"],
    proposalId: "prop-002",
    notes:
      "Healthcare compliance review needed. HIPAA requirements discussed.",
    createdAt: "2026-01-08T09:00:00Z",
    updatedAt: "2026-02-18T11:00:00Z",
    closedAt: null,
    nextFollowUp: "2026-02-25T15:00:00Z",
  },
  {
    id: "deal-003",
    clientName: "Aisha Patel",
    clientEmail: "aisha@quantumleap.co",
    clientCompany: "QuantumLeap Analytics",
    title: "AI Strategy & Team Training",
    value: 7500,
    stage: "qualified",
    priority: "medium",
    probability: 45,
    serviceIds: ["svc-001", "svc-003"],
    proposalId: null,
    notes:
      "Initial discovery call went well. Team of 12 engineers needs upskilling.",
    createdAt: "2026-02-01T14:00:00Z",
    updatedAt: "2026-02-19T09:00:00Z",
    closedAt: null,
    nextFollowUp: "2026-02-26T11:00:00Z",
  },
  {
    id: "deal-004",
    clientName: "James Okoro",
    clientEmail: "james@finflow.io",
    clientCompany: "FinFlow",
    title: "Fraud Detection Model Development",
    value: 35000,
    stage: "won",
    priority: "high",
    probability: 100,
    serviceIds: ["svc-002", "svc-006"],
    proposalId: "prop-003",
    notes: "Contract signed. Kickoff scheduled for March 1st.",
    createdAt: "2025-11-20T10:00:00Z",
    updatedAt: "2026-02-10T16:00:00Z",
    closedAt: "2026-02-10T16:00:00Z",
    nextFollowUp: null,
  },
  {
    id: "deal-005",
    clientName: "Elena Vasquez",
    clientEmail: "elena@brightpath.edu",
    clientCompany: "BrightPath Education",
    title: "AI Tutor Chatbot",
    value: 22000,
    stage: "proposal",
    priority: "medium",
    probability: 50,
    serviceIds: ["svc-002"],
    proposalId: "prop-004",
    notes: "Proposal sent last week. Follow up scheduled.",
    createdAt: "2026-01-15T13:00:00Z",
    updatedAt: "2026-02-17T10:00:00Z",
    closedAt: null,
    nextFollowUp: "2026-02-28T09:00:00Z",
  },
  {
    id: "deal-006",
    clientName: "David Kim",
    clientEmail: "david@terralogistics.com",
    clientCompany: "Terra Logistics",
    title: "Supply Chain AI Optimization",
    value: 45000,
    stage: "lead",
    priority: "medium",
    probability: 20,
    serviceIds: ["svc-004", "svc-005"],
    proposalId: null,
    notes: "Inbound from website. Initial call scheduled.",
    createdAt: "2026-02-18T08:00:00Z",
    updatedAt: "2026-02-18T08:00:00Z",
    closedAt: null,
    nextFollowUp: "2026-02-25T14:00:00Z",
  },
  {
    id: "deal-007",
    clientName: "Rachel Thompson",
    clientEmail: "rachel@swiftretail.com",
    clientCompany: "Swift Retail",
    title: "Product Recommendation Engine",
    value: 28000,
    stage: "won",
    priority: "high",
    probability: 100,
    serviceIds: ["svc-002", "svc-006"],
    proposalId: "prop-005",
    notes: "Delivered ahead of schedule. Client very satisfied.",
    createdAt: "2025-10-05T10:00:00Z",
    updatedAt: "2026-01-15T12:00:00Z",
    closedAt: "2026-01-15T12:00:00Z",
    nextFollowUp: null,
  },
  {
    id: "deal-008",
    clientName: "Omar Hassan",
    clientEmail: "omar@cloudnine.dev",
    clientCompany: "CloudNine",
    title: "AI Infrastructure Assessment",
    value: 8000,
    stage: "lost",
    priority: "low",
    probability: 0,
    serviceIds: ["svc-004"],
    proposalId: "prop-006",
    notes: "Lost to competitor. Budget constraints cited.",
    createdAt: "2025-12-01T11:00:00Z",
    updatedAt: "2026-01-20T09:00:00Z",
    closedAt: "2026-01-20T09:00:00Z",
    nextFollowUp: null,
  },
];

// ─── Proposals ───

export const seedProposals: Proposal[] = [
  {
    id: "prop-001",
    dealId: "deal-001",
    clientName: "Sarah Chen",
    clientCompany: "Meridian Technologies",
    title: "Enterprise AI Platform Proposal",
    status: "viewed",
    lineItems: [
      {
        serviceId: "svc-005",
        serviceName: "Enterprise AI Platform",
        quantity: 1,
        unitPrice: 50000,
        total: 50000,
        notes: "Full platform build with custom models",
      },
      {
        serviceId: "svc-006",
        serviceName: "Ongoing AI Support",
        quantity: 1,
        unitPrice: 2000,
        total: 2000,
        notes: "First month included",
      },
    ],
    subtotal: 52000,
    discount: 0,
    total: 52000,
    validUntil: "2026-03-15T00:00:00Z",
    scopeNotes:
      "Includes platform architecture, custom model development, data pipeline engineering, and 6-month support.",
    createdAt: "2026-01-10T10:00:00Z",
    sentAt: "2026-01-12T09:00:00Z",
  },
  {
    id: "prop-002",
    dealId: "deal-002",
    clientName: "Marcus Rivera",
    clientCompany: "NovaHealth",
    title: "LLM Patient Triage System Proposal",
    status: "sent",
    lineItems: [
      {
        serviceId: "svc-002",
        serviceName: "Custom LLM Integration",
        quantity: 1,
        unitPrice: 15000,
        total: 15000,
        notes: "HIPAA-compliant triage model",
      },
      {
        serviceId: "svc-004",
        serviceName: "AI Infrastructure Audit",
        quantity: 1,
        unitPrice: 3500,
        total: 3500,
        notes: "Discounted as bundle",
      },
    ],
    subtotal: 18500,
    discount: 0,
    total: 18500,
    validUntil: "2026-03-20T00:00:00Z",
    scopeNotes:
      "Healthcare-grade LLM integration with HIPAA compliance review and infrastructure assessment.",
    createdAt: "2026-02-05T14:00:00Z",
    sentAt: "2026-02-06T10:00:00Z",
  },
  {
    id: "prop-003",
    dealId: "deal-004",
    clientName: "James Okoro",
    clientCompany: "FinFlow",
    title: "Fraud Detection Model Proposal",
    status: "accepted",
    lineItems: [
      {
        serviceId: "svc-002",
        serviceName: "Custom LLM Integration",
        quantity: 1,
        unitPrice: 15000,
        total: 15000,
        notes: "Fraud detection model",
      },
      {
        serviceId: "svc-006",
        serviceName: "Ongoing AI Support",
        quantity: 4,
        unitPrice: 5000,
        total: 20000,
        notes: "4 months support included",
      },
    ],
    subtotal: 35000,
    discount: 0,
    total: 35000,
    validUntil: "2026-02-28T00:00:00Z",
    scopeNotes:
      "Custom fraud detection with real-time scoring and model monitoring.",
    createdAt: "2026-01-05T10:00:00Z",
    sentAt: "2026-01-06T09:00:00Z",
  },
  {
    id: "prop-004",
    dealId: "deal-005",
    clientName: "Elena Vasquez",
    clientCompany: "BrightPath Education",
    title: "AI Tutor Chatbot Proposal",
    status: "sent",
    lineItems: [
      {
        serviceId: "svc-002",
        serviceName: "Custom LLM Integration",
        quantity: 1,
        unitPrice: 15000,
        total: 15000,
        notes: "Educational AI tutor chatbot",
      },
      {
        serviceId: "svc-003",
        serviceName: "AI Team Training",
        quantity: 1,
        unitPrice: 3000,
        total: 3000,
        notes: "Team onboarding",
      },
    ],
    subtotal: 18000,
    discount: 0,
    total: 18000,
    validUntil: "2026-03-10T00:00:00Z",
    scopeNotes:
      "AI-powered tutoring chatbot with subject-specific knowledge bases.",
    createdAt: "2026-02-10T11:00:00Z",
    sentAt: "2026-02-11T08:00:00Z",
  },
  {
    id: "prop-005",
    dealId: "deal-007",
    clientName: "Rachel Thompson",
    clientCompany: "Swift Retail",
    title: "Recommendation Engine Proposal",
    status: "accepted",
    lineItems: [
      {
        serviceId: "svc-002",
        serviceName: "Custom LLM Integration",
        quantity: 1,
        unitPrice: 15000,
        total: 15000,
        notes: "Product recommendation engine",
      },
      {
        serviceId: "svc-006",
        serviceName: "Ongoing AI Support",
        quantity: 2,
        unitPrice: 5000,
        total: 10000,
        notes: "Ongoing optimization",
      },
    ],
    subtotal: 25000,
    discount: 0,
    total: 25000,
    validUntil: "2025-12-31T00:00:00Z",
    scopeNotes:
      "ML-powered product recommendations with A/B testing framework.",
    createdAt: "2025-10-15T10:00:00Z",
    sentAt: "2025-10-16T09:00:00Z",
  },
  {
    id: "prop-006",
    dealId: "deal-008",
    clientName: "Omar Hassan",
    clientCompany: "CloudNine",
    title: "Infrastructure Assessment Proposal",
    status: "rejected",
    lineItems: [
      {
        serviceId: "svc-004",
        serviceName: "AI Infrastructure Audit",
        quantity: 1,
        unitPrice: 8000,
        total: 8000,
        notes: "Full infrastructure review",
      },
    ],
    subtotal: 8000,
    discount: 0,
    total: 8000,
    validUntil: "2026-01-15T00:00:00Z",
    scopeNotes: "Comprehensive AI infrastructure and cost assessment.",
    createdAt: "2025-12-10T09:00:00Z",
    sentAt: "2025-12-11T08:00:00Z",
  },
];

// ─── Activity Feed ───

export const seedActivities: ActivityItem[] = [
  {
    id: "act-001",
    type: "deal_created",
    dealId: "deal-006",
    dealTitle: "Supply Chain AI Optimization",
    description: "New lead from website: Terra Logistics",
    timestamp: "2026-02-18T08:00:00Z",
  },
  {
    id: "act-002",
    type: "proposal_viewed",
    dealId: "deal-001",
    dealTitle: "Enterprise AI Platform Build",
    description: "Sarah Chen viewed the proposal for the third time",
    timestamp: "2026-02-20T14:30:00Z",
  },
  {
    id: "act-003",
    type: "deal_moved",
    dealId: "deal-002",
    dealTitle: "LLM-Powered Patient Triage",
    description: "Moved from Qualified to Proposal stage",
    timestamp: "2026-02-18T11:00:00Z",
  },
  {
    id: "act-004",
    type: "deal_won",
    dealId: "deal-004",
    dealTitle: "Fraud Detection Model Development",
    description: "Deal closed for $35,000 with FinFlow",
    timestamp: "2026-02-10T16:00:00Z",
  },
  {
    id: "act-005",
    type: "proposal_sent",
    dealId: "deal-005",
    dealTitle: "AI Tutor Chatbot",
    description: "Proposal sent to Elena Vasquez at BrightPath",
    timestamp: "2026-02-11T08:00:00Z",
  },
  {
    id: "act-006",
    type: "follow_up_scheduled",
    dealId: "deal-003",
    dealTitle: "AI Strategy & Team Training",
    description: "Follow-up call scheduled for Feb 26",
    timestamp: "2026-02-19T09:00:00Z",
  },
  {
    id: "act-007",
    type: "note_added",
    dealId: "deal-001",
    dealTitle: "Enterprise AI Platform Build",
    description: "Added note: Waiting on legal review from Meridian",
    timestamp: "2026-02-19T15:00:00Z",
  },
  {
    id: "act-008",
    type: "deal_lost",
    dealId: "deal-008",
    dealTitle: "AI Infrastructure Assessment",
    description: "Lost to competitor — budget constraints",
    timestamp: "2026-01-20T09:00:00Z",
  },
];

// ─── Testimonials ───

export const seedTestimonials: Testimonial[] = [
  {
    id: "test-001",
    name: "James Okoro",
    role: "CTO",
    company: "FinFlow",
    quote:
      "DealForge transformed how we sell AI services. We went from spreadsheets and guesswork to a professional pipeline that actually converts. Our close rate jumped 40% in the first quarter.",
    revenue: "$420K closed in Q1",
    avatarInitials: "JO",
  },
  {
    id: "test-002",
    name: "Rachel Thompson",
    role: "Founder",
    company: "Swift Retail",
    quote:
      "The proposal generator alone is worth 10x the price. What used to take me 3 hours now takes 60 seconds. My clients are impressed and I'm closing deals faster than ever.",
    revenue: "$280K annual recurring",
    avatarInitials: "RT",
  },
  {
    id: "test-003",
    name: "Priya Sharma",
    role: "Head of AI Consulting",
    company: "Nexus Partners",
    quote:
      "We scaled from 2 to 15 active deals without adding headcount. DealForge gives us the infrastructure to look and operate like an enterprise while staying lean and fast.",
    revenue: "$1.2M pipeline value",
    avatarInitials: "PS",
  },
];

// ─── Revenue ticker data ───

export const revenueTickerItems = [
  { label: "FinFlow", amount: "$35,000", type: "won" as const },
  { label: "Swift Retail", amount: "$28,000", type: "won" as const },
  { label: "Meridian Tech", amount: "$52,000", type: "pipeline" as const },
  { label: "NovaHealth", amount: "$18,500", type: "pipeline" as const },
  { label: "BrightPath", amount: "$22,000", type: "pipeline" as const },
  { label: "Nexus Partners", amount: "$67,000", type: "won" as const },
  { label: "Atlas Corp", amount: "$41,000", type: "won" as const },
  { label: "Vertex AI", amount: "$33,500", type: "pipeline" as const },
];
